version: '1'

networks:
  kafka-network:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    container_name: zookeeper
    networks:
      - kafka-network
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: 'bitnami/kafka:3.1.0'
    container_name: kafka
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_NUM_NETWORK_THREADS: 3
      KAFKA_CFG_NUM_IO_THREADS: 8
      KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_CFG_LOG_DIRS: /tmp/kafka-logs
      KAFKA_CFG_NUM_PARTITIONS: 1
      KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 18000


  kafka-connect:
    image: 'confluentinc/cp-kafka-connect-base:7.0.1'
    container_name: kafka-connect
    networks:
      - kafka-network
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8083:8083
      - 8888:8888
    volumes:
      - ./target:/usr/share/java/kafka-connect-sample
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONNECT_REST_PORT: 8083
      KAFKA_DEBUG: true
      JAVA_DEBUG_PORT: '*:8888'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'connect'
      CONNECT_GROUP_ID: kafka-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offset
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
#      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
#      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_KEY_CONVERTER: 'org.apache.kafka.connect.storage.StringConverter'
      CONNECT_VALUE_CONVERTER: 'org.apache.kafka.connect.storage.StringConverter'
      CONNECT_LOG4J_ROOT_LOGLEVEL: 'INFO'
      CONNECT_LOG4J_LOGGERS: 'org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_PLUGIN_PATH: '/usr/share/java'
